name: Deploy backend-ta
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t kevinh66/ta-back-end .
      - name: Publish Image to docker hub
        run: docker push kevinh66/ta-back-end:latest

  deploy:
      needs: build
      runs-on: self-hosted 
      steps:
        - name: Pull image from docker hub
          run: docker pull kevinh66/ta-back-end:latest
        - name: Run Docker Container
          run: docker run -d -p 5001:5001 --name ta-back-end-container \
            -e MONGO_URI='${{ secrets.MONGO_URI }}' \
            -e RESEND_API_KEY='${{ secrets.RESEND_API_KEY }}' \
            -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
            kevinh66/ta-back-end
        - name: Check logs
          run: docker logs ta-back-end-container